### ISSUE TITLE
recipe-list

### ISSUE THREAD

**Issue by badabam** [badabam/hh-web-22-2-example-board#1]
### Value statement
As a *user*
I want to *save a list of recipes*
so that *I don't forget them.*

### Description
<img src="https://user-images.githubusercontent.com/157286/169052392-d6290ebf-743c-4013-b4c7-cfb1fe92339d.png" width="300">

### Acceptance criteria
- [ ] The input must be `required`
- [ ] max-length must 100 characters
- [ ] text should wrap on space characters
- [ ] text should scroll in a single line, if needed
- [ ] whitespace should be trimmed
- [ ] the list should scroll behind the form (form has a white background)

### Tasks
- [ ] Create a branch
- [ ] Create component `Recipe`
- [ ] Create component `Button`
- [ ] Create component `RecipeForm`
- [ ] Add logic to create recipes from form
- [ ] Check on a real device

### Complexity
low, medium, high
